apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aniruddhapvc
  namespace: aniruddha-choudhury
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 20Gi
